
CREATE DATABASE IF NOT EXISTS `lecture`;   -- 강의 관련 데이터베이스 (강의 정보 및 강의 콘텐츠 저장)
CREATE DATABASE IF NOT EXISTS `order`;     -- 결제 관련 데이터베이스 (결제 기록 저장)
CREATE DATABASE IF NOT EXISTS `user`;      -- 사용자 관련 데이터베이스 (사용자 정보 및 강사 정보 저장)
CREATE DATABASE IF NOT EXISTS `notitable`;

-- 사용 데이터베이스 설정: 사용자 관련 테이블을 'user' 데이터베이스에 생성한다.
USE `user`;

-- 1. users 테이블 (변경 없음)
CREATE TABLE IF NOT EXISTS users (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,                   
    email VARCHAR(255) NOT NULL UNIQUE,                   
    password VARCHAR(255) NULL,                           
    nickname VARCHAR(100) NOT NULL,
    phone_number VARCHAR(20) NULL,   
    role ENUM('STUDENT', 'INSTRUCTOR', 'ADMIN') NOT NULL DEFAULT 'STUDENT',
    provider ENUM('LOCAL', 'GOOGLE', 'NAVER', 'KAKAO') NOT NULL DEFAULT 'LOCAL',  
    provider_id VARCHAR(1024) NULL,                       
    profile_image VARCHAR(1024) NULL,                    
    status ENUM('ACTIVE', 'INACTIVE', 'BANNED') NOT NULL DEFAULT 'ACTIVE',  
    status_changed_at TIMESTAMP NULL DEFAULT NULL, 
    last_login_at TIMESTAMP NULL DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. teachers 테이블 (id → users.id와 동일한 PK이자 FK)
CREATE TABLE IF NOT EXISTS teachers (
    id BIGINT PRIMARY KEY,                                 -- user_id와 동일
    name VARCHAR(100) NOT NULL,                            -- 신청 시 이름
    bio TEXT NOT NULL,                                     -- 자기소개
    category VARCHAR(50) NOT NULL,                         -- 카테고리
    profile_image VARCHAR(1024) DEFAULT NULL,               -- S3 URL
    resume_file VARCHAR(1024) DEFAULT NULL,                 -- S3 URL
    rating FLOAT DEFAULT 0.0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    teacher_status ENUM('PENDING', 'APPROVED', 'REJECTED') DEFAULT 'PENDING',

    CONSTRAINT fk_teacher_user FOREIGN KEY (id) REFERENCES users(id)
    ON DELETE CASCADE ON UPDATE CASCADE
);

-- 3. email_verification 테이블 생성
CREATE TABLE IF NOT EXISTS email_verification (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR(255) NOT NULL,
    code VARCHAR(10) NOT NULL,
    is_verified BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY unique_email (email)  -- 이메일 당 하나의 코드만 존재하도록 설정
);

USE `lecture`;

-- 4. product 테이블 생성 (강의 정보 저장)
CREATE TABLE IF NOT EXISTS product (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,         -- 강의 고유 ID (Primary Key)
    instructor_id BIGINT NOT NULL,                -- 강사 ID (teachers 테이블의 id 참조)
    title VARCHAR(255) NOT NULL,                  -- 강의 제목
    description TEXT NOT NULL,                    -- 강의 설명
    price INT NOT NULL,                           -- 강의 가격
    category VARCHAR(100) NOT NULL,               -- 강의 카테고리 (예: 프로그래밍, 디자인 등)
    thumbnail_url VARCHAR(1024) DEFAULT NULL,     -- 강의 썸네일 이미지 URL
    video_url VARCHAR(1024),                      -- 강의 동영상 URL
    instructor_name VARCHAR(255) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, -- 강의 등록일
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,  -- 마지막 수정일 (자동 업데이트)
    status ENUM('PENDING', 'APPROVED', 'REJECTED') DEFAULT 'PENDING'  -- 강의 승인 상태
);

-- 5. product_contents 테이블 생성 (강의 내용 저장)
CREATE TABLE IF NOT EXISTS product_contents (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,                    -- 강의 콘텐츠 고유 ID (Primary Key)
    product_id BIGINT NOT NULL,                              -- 강의 ID (product 테이블의 id 참조)
    section INT NOT NULL,                                    -- 강의 섹션 번호 (순서 지정)
    title VARCHAR(255) NOT NULL,                             -- 강의 섹션 제목
    content TEXT,                                            -- 강의 내용 (텍스트 혹은 Markdown 형식)
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,          -- 콘텐츠 등록일
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP  -- 콘텐츠 수정일 (자동 업데이트)
);

-- 사용 데이터베이스 설정: 결제 관련 테이블을 'order' 데이터베이스에 생성한다.
USE `order`;

-- 6. purchase 테이블 생성 (결제 기록 저장)
CREATE TABLE IF NOT EXISTS purchase (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,                             -- 결제 고유 ID (Primary Key)
    user_id BIGINT NOT NULL,                                          -- 결제를 한 사용자 ID (user.users 테이블의 id 참조)
    product_id BIGINT NOT NULL,                                       -- 구매한 강의 ID (lectures.product 테이블의 id 참조)
    merchant_uid VARCHAR(50) UNIQUE NOT NULL,                         -- 주문 고유 번호: 결제 완료 이후 결제 기록 조회나 위변조 대사 작업 시 사용
    imp_uid VARCHAR(255),                                             -- 포트원 결제 고유 번호 (검증용)
    product_price INT NOT NULL ,                                      -- 구매한 강의 가격
    paid_amount INT NOT NULL ,                                        -- 결제된 금액
    payment_method VARCHAR(50) NOT NULL,                              -- 결제 방식 (예: CREDIT_CARD, PAYPAL, KAKAO_PAY 등)
    status ENUM('PENDING', 'COMPLETED', 'FAILED', 'CANCELED', 'ROLLBACK_REQUESTED', 'REFUNDED'),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,                   -- 결제 일시
    is_verified BOOLEAN DEFAULT FALSE,
    reason VARCHAR(255) NULL COMMENT '상태 변경 이유 (검증 시도 실패, 롤백 시도 실패 등)',
    FOREIGN KEY (user_id) REFERENCES user.users(id)
    ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (product_id) REFERENCES lecture.product(id)
);

-- 7. rollback_failure 테이블 생성 (롤백 실패 저장)
CREATE TABLE IF NOT EXISTS rollback_failure (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    purchase_id BIGINT NOT NULL,                    -- purchase table의 PK인 id 값이지만 따로 관리하기 위해 fk 사용 x
    imp_uid VARCHAR(255) NOT NULL,
    amount INT NOT NULL,                            -- 결제된 금액
    reason TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 8. 사용자 취소 실패를 저장하는 테이블
CREATE TABLE IF NOT EXISTS cancel_failure (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    purchase_id BIGINT NOT NULL,             -- purchase 테이블의 PK, fk 없이 저장
    imp_uid VARCHAR(255) NOT NULL,           -- PortOne imp_uid
    amount INT NOT NULL,                     -- 결제된 금액
    reason TEXT,                             -- 실패 이유 (ex. DB save 실패 메시지)
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE discount_rollback_failure (
		id BIGINT AUTO_INCREMENT PRIMARY KEY,
	  product_id BIGINT NOT NULL,
    purchase_id BIGINT NOT NULL,
    reason TEXT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

USE `notitable`;

CREATE TABLE IF NOT EXISTS notification (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    channel ENUM('EMAIL', 'PUSH') NOT NULL,
    recipient_type VARCHAR(20) NOT NULL, -- ALL, STUDENTS, INSTRUCTORS
    title VARCHAR(255),
    content TEXT NOT NULL,
    status ENUM('PENDING', 'QUEUED', 'SENT', 'FAILED') DEFAULT 'PENDING',
    error_message TEXT,
    scheduled_at DATETIME,
    sent_at DATETIME,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS notification_delivery_log (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    notification_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    status ENUM('SENT', 'FAILED') NOT NULL,
    error_message TEXT,
    sent_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(notification_id, user_id)
);

CREATE TABLE IF NOT EXISTS user_push_token (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    fcm_token TEXT NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT uniq_user_id UNIQUE (user_id) -- ✅ 중복 방지용
);

CREATE TABLE IF NOT EXISTS user_contact (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    phone VARCHAR(20) NOT NULL,
    is_verified BOOLEAN DEFAULT TRUE,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_email (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    email VARCHAR(255) NOT NULL,
    is_verified BOOLEAN DEFAULT TRUE,
    is_subscribed BOOLEAN DEFAULT TRUE,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

USE `user`;

-- users 테이블 더미 데이터
INSERT INTO users (email, password, nickname, phone_number, role, provider, provider_id, status, status_changed_at, last_login_at)
VALUES
('admin@example.com', '$2a$10$nSbmA8.arG6BzMADtkA2bOQW9oYNXSZ7NXeEBGiLH4gCa3HnK585a', 'admin', '010-0000-0000', 'ADMIN', 'LOCAL', NULL, 'ACTIVE', NOW(), NOW()),
('student@example.com', '$2a$10$nSbmA8.arG6BzMADtkA2bOQW9oYNXSZ7NXeEBGiLH4gCa3HnK585a', 'student_user', '010-1111-1111', 'STUDENT', 'LOCAL', NULL, 'ACTIVE', NOW(), NOW()),
('instructor3@example.com', '$2a$10$nSbmA8.arG6BzMADtkA2bOQW9oYNXSZ7NXeEBGiLH4gCa3HnK585a', '이영길', '010-3333-3303', 'INSTRUCTOR', 'LOCAL', NULL, 'ACTIVE', NOW(), NOW()),
('instructor4@example.com', '$2a$10$nSbmA8.arG6BzMADtkA2bOQW9oYNXSZ7NXeEBGiLH4gCa3HnK585a', '이민재', '010-3333-3304', 'INSTRUCTOR', 'LOCAL', NULL, 'ACTIVE', NOW(), NOW()),
('instructor5@example.com', '$2a$10$nSbmA8.arG6BzMADtkA2bOQW9oYNXSZ7NXeEBGiLH4gCa3HnK585a', '김상철', '010-3333-3305', 'INSTRUCTOR', 'LOCAL', NULL, 'ACTIVE', NOW(), NOW()),
('instructor6@example.com', '$2a$10$nSbmA8.arG6BzMADtkA2bOQW9oYNXSZ7NXeEBGiLH4gCa3HnK585a', '김현숙', '010-3333-3306', 'INSTRUCTOR', 'LOCAL', NULL, 'ACTIVE', NOW(), NOW()),
('instructor7@example.com', '$2a$10$nSbmA8.arG6BzMADtkA2bOQW9oYNXSZ7NXeEBGiLH4gCa3HnK585a', '곽정남', '010-3333-3307', 'INSTRUCTOR', 'LOCAL', NULL, 'ACTIVE', NOW(), NOW()),
('instructor8@example.com', '$2a$10$nSbmA8.arG6BzMADtkA2bOQW9oYNXSZ7NXeEBGiLH4gCa3HnK585a', '박현우', '010-3333-3308', 'INSTRUCTOR', 'LOCAL', NULL, 'ACTIVE', NOW(), NOW()),
('instructor9@example.com', '$2a$10$nSbmA8.arG6BzMADtkA2bOQW9oYNXSZ7NXeEBGiLH4gCa3HnK585a', '고예준', '010-3333-3309', 'INSTRUCTOR', 'LOCAL', NULL, 'ACTIVE', NOW(), NOW()),
('instructor10@example.com', '$2a$10$nSbmA8.arG6BzMADtkA2bOQW9oYNXSZ7NXeEBGiLH4gCa3HnK585a', '이정자', '010-3333-3310', 'INSTRUCTOR', 'LOCAL', NULL, 'ACTIVE', NOW(), NOW()),
('instructor11@example.com', '$2a$10$nSbmA8.arG6BzMADtkA2bOQW9oYNXSZ7NXeEBGiLH4gCa3HnK585a', '황영진', '010-3333-3311', 'INSTRUCTOR', 'LOCAL', NULL, 'ACTIVE', NOW(), NOW()),
('instructor12@example.com', '$2a$10$nSbmA8.arG6BzMADtkA2bOQW9oYNXSZ7NXeEBGiLH4gCa3HnK585a', '김수민', '010-3333-3312', 'INSTRUCTOR', 'LOCAL', NULL, 'ACTIVE', NOW(), NOW()),
('instructor13@example.com', '$2a$10$nSbmA8.arG6BzMADtkA2bOQW9oYNXSZ7NXeEBGiLH4gCa3HnK585a', '최재현', '010-3333-3313', 'INSTRUCTOR', 'LOCAL', NULL, 'ACTIVE', NOW(), NOW()),
('instructor14@example.com', '$2a$10$nSbmA8.arG6BzMADtkA2bOQW9oYNXSZ7NXeEBGiLH4gCa3HnK585a', '김성훈', '010-3333-3314', 'INSTRUCTOR', 'LOCAL', NULL, 'ACTIVE', NOW(), NOW()),
('instructor15@example.com', '$2a$10$nSbmA8.arG6BzMADtkA2bOQW9oYNXSZ7NXeEBGiLH4gCa3HnK585a', '이지훈', '010-3333-3315', 'INSTRUCTOR', 'LOCAL', NULL, 'ACTIVE', NOW(), NOW()),
('instructor16@example.com', '$2a$10$nSbmA8.arG6BzMADtkA2bOQW9oYNXSZ7NXeEBGiLH4gCa3HnK585a', '이정자', '010-3333-3316', 'INSTRUCTOR', 'LOCAL', NULL, 'ACTIVE', NOW(), NOW()),
('instructor17@example.com', '$2a$10$nSbmA8.arG6BzMADtkA2bOQW9oYNXSZ7NXeEBGiLH4gCa3HnK585a', '이성민', '010-3333-3317', 'INSTRUCTOR', 'LOCAL', NULL, 'ACTIVE', NOW(), NOW()),
('instructor18@example.com', '$2a$10$nSbmA8.arG6BzMADtkA2bOQW9oYNXSZ7NXeEBGiLH4gCa3HnK585a', '김중수', '010-3333-3318', 'INSTRUCTOR', 'LOCAL', NULL, 'ACTIVE', NOW(), NOW()),
('instructor19@example.com', '$2a$10$nSbmA8.arG6BzMADtkA2bOQW9oYNXSZ7NXeEBGiLH4gCa3HnK585a', '박경희', '010-3333-3319', 'INSTRUCTOR', 'LOCAL', NULL, 'ACTIVE', NOW(), NOW()),
('instructor20@example.com', '$2a$10$nSbmA8.arG6BzMADtkA2bOQW9oYNXSZ7NXeEBGiLH4gCa3HnK585a', '김옥자', '010-3333-3320', 'INSTRUCTOR', 'LOCAL', NULL, 'ACTIVE', NOW(), NOW()),
('instructor21@example.com', '$2a$10$nSbmA8.arG6BzMADtkA2bOQW9oYNXSZ7NXeEBGiLH4gCa3HnK585a', '성미경', '010-3333-3321', 'INSTRUCTOR', 'LOCAL', NULL, 'ACTIVE', NOW(), NOW()),
('instructor22@example.com', '$2a$10$nSbmA8.arG6BzMADtkA2bOQW9oYNXSZ7NXeEBGiLH4gCa3HnK585a', '이경희', '010-3333-3322', 'INSTRUCTOR', 'LOCAL', NULL, 'ACTIVE', NOW(), NOW()),
('instructor23@example.com', '$2a$10$nSbmA8.arG6BzMADtkA2bOQW9oYNXSZ7NXeEBGiLH4gCa3HnK585a', '오경수', '010-3333-3323', 'INSTRUCTOR', 'LOCAL', NULL, 'ACTIVE', NOW(), NOW()),
('instructor24@example.com', '$2a$10$nSbmA8.arG6BzMADtkA2bOQW9oYNXSZ7NXeEBGiLH4gCa3HnK585a', '박민준', '010-3333-3324', 'INSTRUCTOR', 'LOCAL', NULL, 'ACTIVE', NOW(), NOW()),
('instructor25@example.com', '$2a$10$nSbmA8.arG6BzMADtkA2bOQW9oYNXSZ7NXeEBGiLH4gCa3HnK585a', '김승민', '010-3333-3325', 'INSTRUCTOR', 'LOCAL', NULL, 'ACTIVE', NOW(), NOW()),
('instructor26@example.com', '$2a$10$nSbmA8.arG6BzMADtkA2bOQW9oYNXSZ7NXeEBGiLH4gCa3HnK585a', '최지현', '010-3333-3326', 'INSTRUCTOR', 'LOCAL', NULL, 'ACTIVE', NOW(), NOW()),
('instructor27@example.com', '$2a$10$nSbmA8.arG6BzMADtkA2bOQW9oYNXSZ7NXeEBGiLH4gCa3HnK585a', '문지영', '010-3333-3327', 'INSTRUCTOR', 'LOCAL', NULL, 'ACTIVE', NOW(), NOW()),
('instructor28@example.com', '$2a$10$nSbmA8.arG6BzMADtkA2bOQW9oYNXSZ7NXeEBGiLH4gCa3HnK585a', '이아름', '010-3333-3328', 'INSTRUCTOR', 'LOCAL', NULL, 'ACTIVE', NOW(), NOW()),
('instructor29@example.com', '$2a$10$nSbmA8.arG6BzMADtkA2bOQW9oYNXSZ7NXeEBGiLH4gCa3HnK585a', '권예준', '010-3333-3329', 'INSTRUCTOR', 'LOCAL', NULL, 'ACTIVE', NOW(), NOW()),
('instructor30@example.com', '$2a$10$nSbmA8.arG6BzMADtkA2bOQW9oYNXSZ7NXeEBGiLH4gCa3HnK585a', '오승민', '010-3333-3330', 'INSTRUCTOR', 'LOCAL', NULL, 'ACTIVE', NOW(), NOW()),
('instructor31@example.com', '$2a$10$nSbmA8.arG6BzMADtkA2bOQW9oYNXSZ7NXeEBGiLH4gCa3HnK585a', '배은영', '010-3333-3331', 'INSTRUCTOR', 'LOCAL', NULL, 'ACTIVE', NOW(), NOW()),
('instructor32@example.com', '$2a$10$nSbmA8.arG6BzMADtkA2bOQW9oYNXSZ7NXeEBGiLH4gCa3HnK585a', '김경자', '010-3333-3332', 'INSTRUCTOR', 'LOCAL', NULL, 'ACTIVE', NOW(), NOW()),
('instructor33@example.com', '$2a$10$nSbmA8.arG6BzMADtkA2bOQW9oYNXSZ7NXeEBGiLH4gCa3HnK585a', '강미숙', '010-3333-3333', 'INSTRUCTOR', 'LOCAL', NULL, 'ACTIVE', NOW(), NOW()),
('instructor34@example.com', '$2a$10$nSbmA8.arG6BzMADtkA2bOQW9oYNXSZ7NXeEBGiLH4gCa3HnK585a', '권명숙', '010-3333-3334', 'INSTRUCTOR', 'LOCAL', NULL, 'ACTIVE', NOW(), NOW()),
('instructor35@example.com', '$2a$10$nSbmA8.arG6BzMADtkA2bOQW9oYNXSZ7NXeEBGiLH4gCa3HnK585a', '김예원', '010-3333-3335', 'INSTRUCTOR', 'LOCAL', NULL, 'ACTIVE', NOW(), NOW()),
('instructor36@example.com', '$2a$10$nSbmA8.arG6BzMADtkA2bOQW9oYNXSZ7NXeEBGiLH4gCa3HnK585a', '오준서', '010-3333-3336', 'INSTRUCTOR', 'LOCAL', NULL, 'ACTIVE', NOW(), NOW()),
('instructor37@example.com', '$2a$10$nSbmA8.arG6BzMADtkA2bOQW9oYNXSZ7NXeEBGiLH4gCa3HnK585a', '배재호', '010-3333-3337', 'INSTRUCTOR', 'LOCAL', NULL, 'ACTIVE', NOW(), NOW()),
('instructor38@example.com', '$2a$10$nSbmA8.arG6BzMADtkA2bOQW9oYNXSZ7NXeEBGiLH4gCa3HnK585a', '김지아', '010-3333-3338', 'INSTRUCTOR', 'LOCAL', NULL, 'ACTIVE', NOW(), NOW()),
('instructor39@example.com', '$2a$10$nSbmA8.arG6BzMADtkA2bOQW9oYNXSZ7NXeEBGiLH4gCa3HnK585a', '구성수', '010-3333-3339', 'INSTRUCTOR', 'LOCAL', NULL, 'ACTIVE', NOW(), NOW()),
('instructor40@example.com', '$2a$10$nSbmA8.arG6BzMADtkA2bOQW9oYNXSZ7NXeEBGiLH4gCa3HnK585a', '우영순', '010-3333-3340', 'INSTRUCTOR', 'LOCAL', NULL, 'ACTIVE', NOW(), NOW());
-- teachers 테이블 더미 데이터
INSERT INTO teachers (id, name, bio, category, profile_image, resume_file, rating, teacher_status)
VALUES
(3, '이영길', '이영길 강사는 실무 경험을 바탕으로 한 전문 강의자로 활동하고 있습니다.', 'DEVOPS', 'https://aigongbu-profile-2324.s3.ap-northeast-2.amazonaws.com/instructorProfile/instructorProfile_3.png', 'https://aigongbu-profile-2324.s3.ap-northeast-2.amazonaws.com/resume/john_doe_resume.pdf', 4.9, 'APPROVED'),
(4, '이민재', '이민재 강사는 실무 경험을 바탕으로 한 전문 강의자로 활동하고 있습니다.', 'DEVOPS', 'https://aigongbu-profile-2324.s3.ap-northeast-2.amazonaws.com/instructorProfile/instructorProfile_4.png', 'https://aigongbu-profile-2324.s3.ap-northeast-2.amazonaws.com/resume/john_doe_resume.pdf', 4.4, 'APPROVED'),
(5, '김상철', '김상철 강사는 실무 경험을 바탕으로 한 전문 강의자로 활동하고 있습니다.', 'BACKEND', 'https://aigongbu-profile-2324.s3.ap-northeast-2.amazonaws.com/instructorProfile/instructorProfile_5.png', 'https://aigongbu-profile-2324.s3.ap-northeast-2.amazonaws.com/resume/john_doe_resume.pdf', 4.9, 'APPROVED'),
(6, '김현숙', '김현숙 강사는 실무 경험을 바탕으로 한 전문 강의자로 활동하고 있습니다.', 'FRONTEND', 'https://aigongbu-profile-2324.s3.ap-northeast-2.amazonaws.com/instructorProfile/instructorProfile_6.png', 'https://aigongbu-profile-2324.s3.ap-northeast-2.amazonaws.com/resume/john_doe_resume.pdf', 4.6, 'APPROVED'),
(7, '곽정남', '곽정남 강사는 실무 경험을 바탕으로 한 전문 강의자로 활동하고 있습니다.', 'AI', 'https://aigongbu-profile-2324.s3.ap-northeast-2.amazonaws.com/instructorProfile/instructorProfile_7.png', 'https://aigongbu-profile-2324.s3.ap-northeast-2.amazonaws.com/resume/john_doe_resume.pdf', 4.4, 'APPROVED'),
(8, '박현우', '박현우 강사는 실무 경험을 바탕으로 한 전문 강의자로 활동하고 있습니다.', 'UI-UX', 'https://aigongbu-profile-2324.s3.ap-northeast-2.amazonaws.com/instructorProfile/instructorProfile_8.png', 'https://aigongbu-profile-2324.s3.ap-northeast-2.amazonaws.com/resume/john_doe_resume.pdf', 4.5, 'APPROVED'),
(9, '고예준', '고예준 강사는 실무 경험을 바탕으로 한 전문 강의자로 활동하고 있습니다.', 'AI', 'https://aigongbu-profile-2324.s3.ap-northeast-2.amazonaws.com/instructorProfile/instructorProfile_5.png', 'https://aigongbu-profile-2324.s3.ap-northeast-2.amazonaws.com/resume/john_doe_resume.pdf', 4.8, 'APPROVED'),
(10, '이정자', '이정자 강사는 실무 경험을 바탕으로 한 전문 강의자로 활동하고 있습니다.', 'CLOUD', 'https://aigongbu-profile-2324.s3.ap-northeast-2.amazonaws.com/instructorProfile/instructorProfile_10.png', 'https://aigongbu-profile-2324.s3.ap-northeast-2.amazonaws.com/resume/john_doe_resume.pdf', 4.8, 'APPROVED'),
(11, '황영진', '황영진 강사는 실무 경험을 바탕으로 한 전문 강의자로 활동하고 있습니다.', 'FRONTEND', 'https://aigongbu-profile-2324.s3.ap-northeast-2.amazonaws.com/instructorProfile/instructorProfile_3.png', 'https://aigongbu-profile-2324.s3.ap-northeast-2.amazonaws.com/resume/john_doe_resume.pdf', 4.9, 'APPROVED'),
(12, '김수민', '김수민 강사는 실무 경험을 바탕으로 한 전문 강의자로 활동하고 있습니다.', 'CLOUD', 'https://aigongbu-profile-2324.s3.ap-northeast-2.amazonaws.com/instructorProfile/instructorProfile_4.png', 'https://aigongbu-profile-2324.s3.ap-northeast-2.amazonaws.com/resume/john_doe_resume.pdf', 4.7, 'APPROVED'),
(13, '최재현', '최재현 강사는 실무 경험을 바탕으로 한 전문 강의자로 활동하고 있습니다.', 'BACKEND', 'https://aigongbu-profile-2324.s3.ap-northeast-2.amazonaws.com/instructorProfile/instructorProfile_5.png', 'https://aigongbu-profile-2324.s3.ap-northeast-2.amazonaws.com/resume/john_doe_resume.pdf', 4.7, 'APPROVED'),
(14, '김성훈', '김성훈 강사는 실무 경험을 바탕으로 한 전문 강의자로 활동하고 있습니다.', 'AI', 'https://aigongbu-profile-2324.s3.ap-northeast-2.amazonaws.com/instructorProfile/instructorProfile_6.png', 'https://aigongbu-profile-2324.s3.ap-northeast-2.amazonaws.com/resume/john_doe_resume.pdf', 4.5, 'APPROVED'),
(15, '이지훈', '이지훈 강사는 실무 경험을 바탕으로 한 전문 강의자로 활동하고 있습니다.', 'FRONTEND', 'https://aigongbu-profile-2324.s3.ap-northeast-2.amazonaws.com/instructorProfile/instructorProfile_5.png', 'https://aigongbu-profile-2324.s3.ap-northeast-2.amazonaws.com/resume/john_doe_resume.pdf', 4.6, 'APPROVED'),
(16, '이정자', '이정자 강사는 실무 경험을 바탕으로 한 전문 강의자로 활동하고 있습니다.', 'DATABASE', 'https://aigongbu-profile-2324.s3.ap-northeast-2.amazonaws.com/instructorProfile/instructorProfile_6.png', 'https://aigongbu-profile-2324.s3.ap-northeast-2.amazonaws.com/resume/john_doe_resume.pdf', 4.5, 'APPROVED'),
(17, '이성민', '이성민 강사는 실무 경험을 바탕으로 한 전문 강의자로 활동하고 있습니다.', 'FRONTEND', 'https://aigongbu-profile-2324.s3.ap-northeast-2.amazonaws.com/instructorProfile/instructorProfile_7.png', 'https://aigongbu-profile-2324.s3.ap-northeast-2.amazonaws.com/resume/john_doe_resume.pdf', 4.7, 'APPROVED'),
(18, '김중수', '김중수 강사는 실무 경험을 바탕으로 한 전문 강의자로 활동하고 있습니다.', 'DEVOPS', 'https://aigongbu-profile-2324.s3.ap-northeast-2.amazonaws.com/instructorProfile/instructorProfile_8.png', 'https://aigongbu-profile-2324.s3.ap-northeast-2.amazonaws.com/resume/john_doe_resume.pdf', 4.4, 'APPROVED'),
(19, '박경희', '박경희 강사는 실무 경험을 바탕으로 한 전문 강의자로 활동하고 있습니다.', 'SECURITY', 'https://aigongbu-profile-2324.s3.ap-northeast-2.amazonaws.com/instructorProfile/instructorProfile_5.png', 'https://aigongbu-profile-2324.s3.ap-northeast-2.amazonaws.com/resume/john_doe_resume.pdf', 4.6, 'APPROVED'),
(20, '김옥자', '김옥자 강사는 실무 경험을 바탕으로 한 전문 강의자로 활동하고 있습니다.', 'AI', 'https://aigongbu-profile-2324.s3.ap-northeast-2.amazonaws.com/instructorProfile/instructorProfile_10.png', 'https://aigongbu-profile-2324.s3.ap-northeast-2.amazonaws.com/resume/john_doe_resume.pdf', 4.6, 'APPROVED'),
(21, '성미경', '성미경 강사는 실무 경험을 바탕으로 한 전문 강의자로 활동하고 있습니다.', 'FRONTEND', 'https://aigongbu-profile-2324.s3.ap-northeast-2.amazonaws.com/instructorProfile/instructorProfile_3.png', 'https://aigongbu-profile-2324.s3.ap-northeast-2.amazonaws.com/resume/john_doe_resume.pdf', 4.7, 'APPROVED'),
(22, '이경희', '이경희 강사는 실무 경험을 바탕으로 한 전문 강의자로 활동하고 있습니다.', 'DATABASE', 'https://aigongbu-profile-2324.s3.ap-northeast-2.amazonaws.com/instructorProfile/instructorProfile_4.png', 'https://aigongbu-profile-2324.s3.ap-northeast-2.amazonaws.com/resume/john_doe_resume.pdf', 4.6, 'APPROVED'),
(23, '오경수', '오경수 강사는 실무 경험을 바탕으로 한 전문 강의자로 활동하고 있습니다.', 'UI-UX', 'https://aigongbu-profile-2324.s3.ap-northeast-2.amazonaws.com/instructorProfile/instructorProfile_5.png', 'https://aigongbu-profile-2324.s3.ap-northeast-2.amazonaws.com/resume/john_doe_resume.pdf', 4.8, 'APPROVED'),
(24, '박민준', '박민준 강사는 실무 경험을 바탕으로 한 전문 강의자로 활동하고 있습니다.', 'MOBILE', 'https://aigongbu-profile-2324.s3.ap-northeast-2.amazonaws.com/instructorProfile/instructorProfile_4.png', 'https://aigongbu-profile-2324.s3.ap-northeast-2.amazonaws.com/resume/john_doe_resume.pdf', 4.8, 'APPROVED'),
(25, '김승민', '김승민 강사는 실무 경험을 바탕으로 한 전문 강의자로 활동하고 있습니다.', 'AI', 'https://aigongbu-profile-2324.s3.ap-northeast-2.amazonaws.com/instructorProfile/instructorProfile_5.png', 'https://aigongbu-profile-2324.s3.ap-northeast-2.amazonaws.com/resume/john_doe_resume.pdf', 4.3, 'APPROVED'),
(26, '최지현', '최지현 강사는 실무 경험을 바탕으로 한 전문 강의자로 활동하고 있습니다.', 'UI-UX', 'https://aigongbu-profile-2324.s3.ap-northeast-2.amazonaws.com/instructorProfile/instructorProfile_6.png', 'https://aigongbu-profile-2324.s3.ap-northeast-2.amazonaws.com/resume/john_doe_resume.pdf', 4.5, 'APPROVED'),
(27, '문지영', '문지영 강사는 실무 경험을 바탕으로 한 전문 강의자로 활동하고 있습니다.', 'AI', 'https://aigongbu-profile-2324.s3.ap-northeast-2.amazonaws.com/instructorProfile/instructorProfile_7.png', 'https://aigongbu-profile-2324.s3.ap-northeast-2.amazonaws.com/resume/john_doe_resume.pdf', 4.9, 'APPROVED'),
(28, '이아름', '이아름 강사는 실무 경험을 바탕으로 한 전문 강의자로 활동하고 있습니다.', 'SECURITY', 'https://aigongbu-profile-2324.s3.ap-northeast-2.amazonaws.com/instructorProfile/instructorProfile_8.png', 'https://aigongbu-profile-2324.s3.ap-northeast-2.amazonaws.com/resume/john_doe_resume.pdf', 4.8, 'APPROVED'),
(29, '권예준', '권예준 강사는 실무 경험을 바탕으로 한 전문 강의자로 활동하고 있습니다.', 'DEVOPS', 'https://aigongbu-profile-2324.s3.ap-northeast-2.amazonaws.com/instructorProfile/instructorProfile_5.png', 'https://aigongbu-profile-2324.s3.ap-northeast-2.amazonaws.com/resume/john_doe_resume.pdf', 4.9, 'APPROVED'),
(30, '오승민', '오승민 강사는 실무 경험을 바탕으로 한 전문 강의자로 활동하고 있습니다.', 'MOBILE', 'https://aigongbu-profile-2324.s3.ap-northeast-2.amazonaws.com/instructorProfile/instructorProfile_10.png', 'https://aigongbu-profile-2324.s3.ap-northeast-2.amazonaws.com/resume/john_doe_resume.pdf', 4.4, 'APPROVED'),
(31, '배은영', '배은영 강사는 실무 경험을 바탕으로 한 전문 강의자로 활동하고 있습니다.', 'CLOUD', 'https://aigongbu-profile-2324.s3.ap-northeast-2.amazonaws.com/instructorProfile/instructorProfile_3.png', 'https://aigongbu-profile-2324.s3.ap-northeast-2.amazonaws.com/resume/john_doe_resume.pdf', 4.3, 'APPROVED'),
(32, '김경자', '김경자 강사는 실무 경험을 바탕으로 한 전문 강의자로 활동하고 있습니다.', 'BACKEND', 'https://aigongbu-profile-2324.s3.ap-northeast-2.amazonaws.com/instructorProfile/instructorProfile_4.png', 'https://aigongbu-profile-2324.s3.ap-northeast-2.amazonaws.com/resume/john_doe_resume.pdf', 4.7, 'APPROVED'),
(33, '강미숙', '강미숙 강사는 실무 경험을 바탕으로 한 전문 강의자로 활동하고 있습니다.', 'CLOUD', 'https://aigongbu-profile-2324.s3.ap-northeast-2.amazonaws.com/instructorProfile/instructorProfile_5.png', 'https://aigongbu-profile-2324.s3.ap-northeast-2.amazonaws.com/resume/john_doe_resume.pdf', 4.8, 'APPROVED'),
(34, '권명숙', '권명숙 강사는 실무 경험을 바탕으로 한 전문 강의자로 활동하고 있습니다.', 'CLOUD', 'https://aigongbu-profile-2324.s3.ap-northeast-2.amazonaws.com/instructorProfile/instructorProfile_4.png', 'https://aigongbu-profile-2324.s3.ap-northeast-2.amazonaws.com/resume/john_doe_resume.pdf', 4.5, 'APPROVED'),
(35, '김예원', '김예원 강사는 실무 경험을 바탕으로 한 전문 강의자로 활동하고 있습니다.', 'AI', 'https://aigongbu-profile-2324.s3.ap-northeast-2.amazonaws.com/instructorProfile/instructorProfile_5.png', 'https://aigongbu-profile-2324.s3.ap-northeast-2.amazonaws.com/resume/john_doe_resume.pdf', 4.4, 'APPROVED'),
(36, '오준서', '오준서 강사는 실무 경험을 바탕으로 한 전문 강의자로 활동하고 있습니다.', 'DEVOPS', 'https://aigongbu-profile-2324.s3.ap-northeast-2.amazonaws.com/instructorProfile/instructorProfile_6.png', 'https://aigongbu-profile-2324.s3.ap-northeast-2.amazonaws.com/resume/john_doe_resume.pdf', 4.9, 'APPROVED'),
(37, '배재호', '배재호 강사는 실무 경험을 바탕으로 한 전문 강의자로 활동하고 있습니다.', 'CLOUD', 'https://aigongbu-profile-2324.s3.ap-northeast-2.amazonaws.com/instructorProfile/instructorProfile_7.png', 'https://aigongbu-profile-2324.s3.ap-northeast-2.amazonaws.com/resume/john_doe_resume.pdf', 4.7, 'APPROVED'),
(38, '김지아', '김지아 강사는 실무 경험을 바탕으로 한 전문 강의자로 활동하고 있습니다.', 'BACKEND', 'https://aigongbu-profile-2324.s3.ap-northeast-2.amazonaws.com/instructorProfile/instructorProfile_8.png', 'https://aigongbu-profile-2324.s3.ap-northeast-2.amazonaws.com/resume/john_doe_resume.pdf', 4.5, 'APPROVED'),
(39, '구성수', '구성수 강사는 실무 경험을 바탕으로 한 전문 강의자로 활동하고 있습니다.', 'UI-UX', 'https://aigongbu-profile-2324.s3.ap-northeast-2.amazonaws.com/instructorProfile/instructorProfile_5.png', 'https://aigongbu-profile-2324.s3.ap-northeast-2.amazonaws.com/resume/john_doe_resume.pdf', 4.7, 'APPROVED'),
(40, '우영순', '우영순 강사는 실무 경험을 바탕으로 한 전문 강의자로 활동하고 있습니다.', 'AI', 'https://aigongbu-profile-2324.s3.ap-northeast-2.amazonaws.com/instructorProfile/instructorProfile_10.png', 'https://aigongbu-profile-2324.s3.ap-northeast-2.amazonaws.com/resume/john_doe_resume.pdf', 4.6, 'APPROVED');

USE `lecture`;

INSERT INTO product (instructor_id, title, description,  price, category, thumbnail_url, video_url, instructor_name, status) 
VALUES 
(3, 'MySQL 완전 정복', '데이터베이스 설계부터 고급 쿼리 작성까지 한 번에 익히는 실전 강의.', 100, 'database', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_10_12.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '이영길', 'APPROVED'),
(3, '안드로이드 앱 개발 실전', 'Kotlin 기반의 앱 개발부터 Play 스토어 배포까지', 150000, 'mobile', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_19_20.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '이영길', 'APPROVED'),
(3, 'REST API 설계와 보안', '효율적인 API 설계, 인증과 인가, 실전 보안 전략까지 한 번에!', 99000, 'backend', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_1_3.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '이영길', 'APPROVED'),
(4, 'DevOps 실전 가이드', 'CI/CD, Docker, Kubernetes까지 한 번에 배우는 실무 DevOps 전략', 99000, 'devops', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_7_9.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '이민재', 'APPROVED'),
(4, 'Node.js로 백엔드 만들기', 'Express와 MongoDB를 활용한 RESTful API 구축 실습', 110000, 'backend', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_5_7.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '이민재', 'APPROVED'),
(4, '스프링 부트로 시작하는 백엔드 개발', '자바 기반의 스프링 부트로 실전 웹 서비스를 만들기 위한 입문 강의입니다.', 120000, 'backend', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_8_10.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '이민재', 'APPROVED'),
(5, 'REST API 설계와 보안', '효율적인 API 설계, 인증과 인가, 실전 보안 전략까지 한 번에!', 99000, 'backend', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_12_14.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '김상철', 'APPROVED'),
(5, 'OAuth2 로그인 시스템 구현', '구글, 네이버, 카카오로 로그인부터 토큰 발급까지 직접 구현해보세요.', 120000, 'security', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_4_6.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '김상철', 'APPROVED'),
(5, 'MySQL 완전 정복', '데이터베이스 설계부터 고급 쿼리 작성까지 한 번에 익히는 실전 강의.', 150000, 'database', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_12_14.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '김상철', 'APPROVED'),
(6, 'OAuth2 로그인 시스템 구현', '구글, 네이버, 카카오로 로그인부터 토큰 발급까지 직접 구현해보세요.', 135000, 'security', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_6_8.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '김현숙', 'APPROVED'),
(6, '초보자를 위한 IntelliJ 완전 활용법', '생산성을 높이는 단축키, 플러그인, 디버깅까지 마스터하는 꿀팁 강의.', 110000, 'other', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_13_15.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '김현숙', 'APPROVED'),
(6, '안드로이드 앱 개발 실전', 'Kotlin 기반의 앱 개발부터 Play 스토어 배포까지', 99000, 'mobile', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_11_13.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '김현숙', 'APPROVED'),
(7, 'React로 만드는 모던 프론트엔드', '컴포넌트 기반 UI부터 상태 관리까지, 실무에 필요한 모든 것을 배웁니다.', 120000, 'frontend', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_10_12.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '곽정남', 'APPROVED'),
(7, 'Git & GitHub 협업 마스터', '팀 프로젝트를 위한 버전 관리와 브랜치 전략, 이젠 제대로 배워보세요.', 150000, 'backend', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_19_20.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '곽정남', 'APPROVED'),
(8, '스프링 부트로 시작하는 백엔드 개발', '자바 기반의 스프링 부트로 실전 웹 서비스를 만들기 위한 입문 강의입니다.', 150000, 'backend', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_22_23.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '박현우', 'APPROVED'),
(8, 'AI로 보는 세상', '딥러닝, 자연어처리, 생성형 AI까지 인공지능의 핵심을 한눈에', 120000, 'ai', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_4_6.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '박현우', 'APPROVED'),
(9, '데이터 사이언스 with Python', 'Pandas, Matplotlib, Scikit-Learn으로 배우는 데이터 분석 A to Z', 150000, 'ai', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_10_12.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '고예준', 'APPROVED'),
(9, 'TypeScript로 탄탄한 프론트엔드 만들기', '타입 안전성과 생산성을 모두 잡는 개발자의 선택!', 110000, 'frontend', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_10_12.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '고예준', 'APPROVED'),
(10, '스프링 부트로 시작하는 백엔드 개발', '자바 기반의 스프링 부트로 실전 웹 서비스를 만들기 위한 입문 강의입니다.', 150000, 'backend', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_3_5.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '이정자', 'APPROVED'),
(10, '초보자를 위한 IntelliJ 완전 활용법', '생산성을 높이는 단축키, 플러그인, 디버깅까지 마스터하는 꿀팁 강의.', 99000, 'other', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_4_6.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '이정자', 'APPROVED'),
(11, 'Git & GitHub 협업 마스터', '팀 프로젝트를 위한 버전 관리와 브랜치 전략, 이젠 제대로 배워보세요.', 99000, 'backend', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_14_16.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '황영진', 'APPROVED'),
(11, 'OAuth2 로그인 시스템 구현', '구글, 네이버, 카카오로 로그인부터 토큰 발급까지 직접 구현해보세요.', 135000, 'security', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_21_22.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '황영진', 'APPROVED'),
(11, '스프링 부트로 시작하는 백엔드 개발', '자바 기반의 스프링 부트로 실전 웹 서비스를 만들기 위한 입문 강의입니다.', 135000, 'backend', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_3_5.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '황영진', 'APPROVED'),
(12, 'React 끝장내기', '컴포넌트 설계부터 상태관리, 최적화까지 프론트엔드 개발자의 필수 강의', 99000, 'frontend', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_7_9.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '김수민', 'APPROVED'),
(12, 'DevOps 실전 가이드', 'CI/CD, Docker, Kubernetes까지 한 번에 배우는 실무 DevOps 전략', 99000, 'devops', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_5_7.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '김수민', 'APPROVED'),
(12, 'iOS 앱 개발 입문', 'Swift와 SwiftUI를 활용한 실습 중심의 모바일 앱 개발 입문 강의', 135000, 'mobile', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_7_9.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '김수민', 'APPROVED'),
(13, '안드로이드 앱 개발 실전', 'Kotlin 기반의 앱 개발부터 Play 스토어 배포까지', 110000, 'mobile', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_17_19.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '최재현', 'APPROVED'),
(13, 'TypeScript로 탄탄한 프론트엔드 만들기', '타입 안전성과 생산성을 모두 잡는 개발자의 선택!', 120000, 'frontend', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_17_19.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '최재현', 'APPROVED'),
(14, '스프링 부트 마스터 클래스', 'API 서버 개발부터 배포까지, 백엔드 실전 프로젝트로 배우는 Spring Boot', 135000, 'backend', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_5_7.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '김성훈', 'APPROVED'),
(14, 'Vue 3 완전 입문', 'Composition API부터 최신 생태계까지, 실습으로 배우는 Vue 3', 120000, 'frontend', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_3_5.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '김성훈', 'APPROVED'),
(15, 'OAuth2 로그인 시스템 구현', '구글, 네이버, 카카오로 로그인부터 토큰 발급까지 직접 구현해보세요.', 150000, 'security', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_20_21.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '이지훈', 'APPROVED'),
(15, 'TypeScript로 탄탄한 프론트엔드 만들기', '타입 안전성과 생산성을 모두 잡는 개발자의 선택!', 150000, 'frontend', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_9_11.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '이지훈', 'APPROVED'),
(15, 'Vue 3 완전 입문', 'Composition API부터 최신 생태계까지, 실습으로 배우는 Vue 3', 99000, 'frontend', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_2_4.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '이지훈', 'APPROVED'),
(16, 'Vue 3 완전 입문', 'Composition API부터 최신 생태계까지, 실습으로 배우는 Vue 3', 110000, 'frontend', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_3_5.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '이정자', 'APPROVED'),
(16, 'AI로 보는 세상', '딥러닝, 자연어처리, 생성형 AI까지 인공지능의 핵심을 한눈에', 110000, 'ai', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_4_6.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '이정자', 'APPROVED'),
(16, 'React로 만드는 모던 프론트엔드', '컴포넌트 기반 UI부터 상태 관리까지, 실무에 필요한 모든 것을 배웁니다.', 120000, 'frontend', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_18_20.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '이정자', 'APPROVED'),
(17, 'OAuth2 로그인 시스템 구현', '구글, 네이버, 카카오로 로그인부터 토큰 발급까지 직접 구현해보세요.', 110000, 'security', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_5_7.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '이성민', 'APPROVED'),
(17, 'AI로 보는 세상', '딥러닝, 자연어처리, 생성형 AI까지 인공지능의 핵심을 한눈에', 120000, 'ai', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_17_19.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '이성민', 'APPROVED'),
(17, 'iOS 앱 개발 입문', 'Swift와 SwiftUI를 활용한 실습 중심의 모바일 앱 개발 입문 강의', 99000, 'mobile', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_8_10.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '이성민', 'APPROVED'),
(18, '데이터 사이언스 with Python', 'Pandas, Matplotlib, Scikit-Learn으로 배우는 데이터 분석 A to Z', 110000, 'ai', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_4_6.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '김중수', 'APPROVED'),
(18, 'React로 만드는 모던 프론트엔드', '컴포넌트 기반 UI부터 상태 관리까지, 실무에 필요한 모든 것을 배웁니다.', 150000, 'frontend', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_21_22.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '김중수', 'APPROVED'),
(19, '안드로이드 앱 개발 실전', 'Kotlin 기반의 앱 개발부터 Play 스토어 배포까지', 135000, 'mobile', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_15_17.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '박경희', 'APPROVED'),
(19, '스프링 부트 마스터 클래스', 'API 서버 개발부터 배포까지, 백엔드 실전 프로젝트로 배우는 Spring Boot', 110000, 'backend', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_5_7.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '박경희', 'APPROVED'),
(19, '데이터 사이언스 with Python', 'Pandas, Matplotlib, Scikit-Learn으로 배우는 데이터 분석 A to Z', 99000, 'ai', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_19_20.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '박경희', 'APPROVED'),
(20, 'REST API 설계와 보안', '효율적인 API 설계, 인증과 인가, 실전 보안 전략까지 한 번에!', 110000, 'backend', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_5_7.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '김옥자', 'APPROVED'),
(20, 'TypeScript로 탄탄한 프론트엔드 만들기', '타입 안전성과 생산성을 모두 잡는 개발자의 선택!', 150000, 'frontend', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_4_6.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '김옥자', 'APPROVED'),
(21, 'MySQL 완전 정복', '데이터베이스 설계부터 고급 쿼리 작성까지 한 번에 익히는 실전 강의.', 135000, 'database', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_7_9.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '성미경', 'APPROVED'),
(21, '초보자를 위한 IntelliJ 완전 활용법', '생산성을 높이는 단축키, 플러그인, 디버깅까지 마스터하는 꿀팁 강의.', 110000, 'other', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_4_6.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '성미경', 'APPROVED'),
(21, 'Git & GitHub 협업 마스터', '팀 프로젝트를 위한 버전 관리와 브랜치 전략, 이젠 제대로 배워보세요.', 150000, 'backend', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_19_20.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '성미경', 'APPROVED'),
(22, 'TypeScript로 탄탄한 프론트엔드 만들기', '타입 안전성과 생산성을 모두 잡는 개발자의 선택!', 99000, 'frontend', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_3_5.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '이경희', 'APPROVED'),
(22, '안드로이드 앱 개발 실전', 'Kotlin 기반의 앱 개발부터 Play 스토어 배포까지', 135000, 'mobile', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_1_3.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '이경희', 'APPROVED'),
(22, '도커로 배우는 컨테이너 개발', '실무에서 바로 써먹는 Docker와 CI/CD 환경 구축 실습!', 120000, 'devops', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_10_12.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '이경희', 'APPROVED'),
(23, 'AWS로 시작하는 클라우드 인프라', 'EC2, S3, RDS, IAM까지 서비스 배포에 꼭 필요한 구성요소를 배워요.', 135000, 'cloud', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_8_10.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '오경수', 'APPROVED'),
(23, 'React 끝장내기', '컴포넌트 설계부터 상태관리, 최적화까지 프론트엔드 개발자의 필수 강의', 135000, 'frontend', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_2_2.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '오경수', 'APPROVED'),
(23, 'OAuth2 로그인 시스템 구현', '구글, 네이버, 카카오로 로그인부터 토큰 발급까지 직접 구현해보세요.', 135000, 'security', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_17_19.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '오경수', 'APPROVED'),
(24, '스프링 부트로 시작하는 백엔드 개발', '자바 기반의 스프링 부트로 실전 웹 서비스를 만들기 위한 입문 강의입니다.', 150000, 'backend', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_7_9.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '박민준', 'APPROVED'),
(24, 'Git & GitHub 협업 마스터', '팀 프로젝트를 위한 버전 관리와 브랜치 전략, 이젠 제대로 배워보세요.', 110000, 'backend', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_22_23.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '박민준', 'APPROVED'),
(25, 'React로 만드는 모던 프론트엔드', '컴포넌트 기반 UI부터 상태 관리까지, 실무에 필요한 모든 것을 배웁니다.', 99000, 'frontend', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_19_20.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '김승민', 'APPROVED'),
(25, 'Vue 3 완전 입문', 'Composition API부터 최신 생태계까지, 실습으로 배우는 Vue 3', 120000, 'frontend', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_21_22.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '김승민', 'APPROVED'),
(26, 'AWS로 시작하는 클라우드 인프라', 'EC2, S3, RDS, IAM까지 서비스 배포에 꼭 필요한 구성요소를 배워요.', 110000, 'cloud', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_8_10.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '최지현', 'APPROVED'),
(26, 'REST API 설계와 보안', '효율적인 API 설계, 인증과 인가, 실전 보안 전략까지 한 번에!', 120000, 'backend', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_16_18.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '최지현', 'APPROVED'),
(27, 'OAuth2 로그인 시스템 구현', '구글, 네이버, 카카오로 로그인부터 토큰 발급까지 직접 구현해보세요.', 110000, 'security', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_2_2.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '문지영', 'APPROVED'),
(27, 'iOS 앱 개발 입문', 'Swift와 SwiftUI를 활용한 실습 중심의 모바일 앱 개발 입문 강의', 99000, 'mobile', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_9_11.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '문지영', 'APPROVED'),
(27, 'Vue 3 완전 입문', 'Composition API부터 최신 생태계까지, 실습으로 배우는 Vue 3', 120000, 'frontend', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_8_10.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '문지영', 'APPROVED'),
(28, 'React로 만드는 모던 프론트엔드', '컴포넌트 기반 UI부터 상태 관리까지, 실무에 필요한 모든 것을 배웁니다.', 110000, 'frontend', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_7_9.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '이아름', 'APPROVED'),
(28, '데이터 사이언스 with Python', 'Pandas, Matplotlib, Scikit-Learn으로 배우는 데이터 분석 A to Z', 110000, 'ai', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_13_15.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '이아름', 'APPROVED'),
(28, '스프링 부트로 시작하는 백엔드 개발', '자바 기반의 스프링 부트로 실전 웹 서비스를 만들기 위한 입문 강의입니다.', 99000, 'backend', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_16_18.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '이아름', 'APPROVED'),
(29, '스프링 부트 마스터 클래스', 'API 서버 개발부터 배포까지, 백엔드 실전 프로젝트로 배우는 Spring Boot', 120000, 'backend', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_1_3.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '권예준', 'APPROVED'),
(29, '데이터 사이언스 with Python', 'Pandas, Matplotlib, Scikit-Learn으로 배우는 데이터 분석 A to Z', 99000, 'ai', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_8_10.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '권예준', 'APPROVED'),
(30, '도커로 배우는 컨테이너 개발', '실무에서 바로 써먹는 Docker와 CI/CD 환경 구축 실습!', 110000, 'devops', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_4_6.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '오승민', 'APPROVED'),
(30, 'REST API 설계와 보안', '효율적인 API 설계, 인증과 인가, 실전 보안 전략까지 한 번에!', 135000, 'backend', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_9_11.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '오승민', 'APPROVED'),
(30, 'iOS 앱 개발 입문', 'Swift와 SwiftUI를 활용한 실습 중심의 모바일 앱 개발 입문 강의', 110000, 'mobile', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_9_11.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '오승민', 'APPROVED'),
(31, '스프링 부트로 시작하는 백엔드 개발', '자바 기반의 스프링 부트로 실전 웹 서비스를 만들기 위한 입문 강의입니다.', 110000, 'backend', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_1_3.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '배은영', 'APPROVED'),
(31, 'AI로 보는 세상', '딥러닝, 자연어처리, 생성형 AI까지 인공지능의 핵심을 한눈에', 120000, 'ai', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_5_7.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '배은영', 'APPROVED'),
(31, '스프링 부트 마스터 클래스', 'API 서버 개발부터 배포까지, 백엔드 실전 프로젝트로 배우는 Spring Boot', 110000, 'backend', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_3_5.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '배은영', 'APPROVED'),
(32, 'Vue 3 완전 입문', 'Composition API부터 최신 생태계까지, 실습으로 배우는 Vue 3', 150000, 'frontend', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_7_9.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '김경자', 'APPROVED'),
(32, 'React 끝장내기', '컴포넌트 설계부터 상태관리, 최적화까지 프론트엔드 개발자의 필수 강의', 99000, 'frontend', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_3_5.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '김경자', 'APPROVED'),
(33, 'Vue 3 완전 입문', 'Composition API부터 최신 생태계까지, 실습으로 배우는 Vue 3', 99000, 'frontend', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_12_14.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '강미숙', 'APPROVED'),
(33, 'DevOps 실전 가이드', 'CI/CD, Docker, Kubernetes까지 한 번에 배우는 실무 DevOps 전략', 135000, 'devops', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_5_7.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '강미숙', 'APPROVED'),
(34, 'React 끝장내기', '컴포넌트 설계부터 상태관리, 최적화까지 프론트엔드 개발자의 필수 강의', 135000, 'frontend', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_22_23.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '권명숙', 'APPROVED'),
(34, 'Vue 3 완전 입문', 'Composition API부터 최신 생태계까지, 실습으로 배우는 Vue 3', 110000, 'frontend', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_7_9.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '권명숙', 'APPROVED'),
(34, 'MySQL 완전 정복', '데이터베이스 설계부터 고급 쿼리 작성까지 한 번에 익히는 실전 강의.', 99000, 'database', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_10_12.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '권명숙', 'APPROVED'),
(35, 'MySQL 완전 정복', '데이터베이스 설계부터 고급 쿼리 작성까지 한 번에 익히는 실전 강의.', 135000, 'database', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_12_14.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '김예원', 'APPROVED'),
(35, '데이터 사이언스 with Python', 'Pandas, Matplotlib, Scikit-Learn으로 배우는 데이터 분석 A to Z', 135000, 'ai', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_12_14.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '김예원', 'APPROVED'),
(35, '스프링 부트로 시작하는 백엔드 개발', '자바 기반의 스프링 부트로 실전 웹 서비스를 만들기 위한 입문 강의입니다.', 120000, 'backend', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_10_12.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '김예원', 'APPROVED'),
(36, '도커로 배우는 컨테이너 개발', '실무에서 바로 써먹는 Docker와 CI/CD 환경 구축 실습!', 110000, 'devops', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_5_7.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '오준서', 'APPROVED'),
(36, 'OAuth2 로그인 시스템 구현', '구글, 네이버, 카카오로 로그인부터 토큰 발급까지 직접 구현해보세요.', 99000, 'security', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_6_8.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '오준서', 'APPROVED'),
(37, '스프링 부트로 시작하는 백엔드 개발', '자바 기반의 스프링 부트로 실전 웹 서비스를 만들기 위한 입문 강의입니다.', 150000, 'backend', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_16_18.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '배재호', 'APPROVED'),
(37, 'React 끝장내기', '컴포넌트 설계부터 상태관리, 최적화까지 프론트엔드 개발자의 필수 강의', 150000, 'frontend', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_2_4.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '배재호', 'APPROVED'),
(37, 'REST API 설계와 보안', '효율적인 API 설계, 인증과 인가, 실전 보안 전략까지 한 번에!', 150000, 'backend', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_2_2.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '배재호', 'APPROVED'),
(38, '도커로 배우는 컨테이너 개발', '실무에서 바로 써먹는 Docker와 CI/CD 환경 구축 실습!', 99000, 'devops', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_16_18.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '김지아', 'APPROVED'),
(38, 'TypeScript로 탄탄한 프론트엔드 만들기', '타입 안전성과 생산성을 모두 잡는 개발자의 선택!', 120000, 'frontend', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_16_18.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '김지아', 'APPROVED'),
(38, '데이터 사이언스 with Python', 'Pandas, Matplotlib, Scikit-Learn으로 배우는 데이터 분석 A to Z', 150000, 'ai', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_13_15.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '김지아', 'APPROVED'),
(39, '데이터 사이언스 with Python', 'Pandas, Matplotlib, Scikit-Learn으로 배우는 데이터 분석 A to Z', 150000, 'ai', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_6_8.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '구성수', 'APPROVED'),
(39, 'REST API 설계와 보안', '효율적인 API 설계, 인증과 인가, 실전 보안 전략까지 한 번에!', 120000, 'backend', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_1_3.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '구성수', 'APPROVED'),
(40, 'React 끝장내기', '컴포넌트 설계부터 상태관리, 최적화까지 프론트엔드 개발자의 필수 강의', 110000, 'frontend', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_15_17.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '우영순', 'APPROVED'),
(40, 'React로 만드는 모던 프론트엔드', '컴포넌트 기반 UI부터 상태 관리까지, 실무에 필요한 모든 것을 배웁니다.', 120000, 'frontend', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/thumbnails/thumbnails_6_8.png', 'https://aigongbu-lecture-files.s3.ap-northeast-2.amazonaws.com/videos/lecture_1_2.mp4', '우영순', 'APPROVED');
-- 강의 콘텐츠 삽입
INSERT INTO product_contents (product_id, section, title, content) 
VALUES 
(1, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(1, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(1, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(1, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(1, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(2, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(2, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(2, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(2, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(2, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(3, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(3, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(3, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(3, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(3, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(4, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(4, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(4, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(4, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(4, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(5, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(5, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(5, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(5, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(5, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(6, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(6, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(6, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(6, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(6, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(7, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(7, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(7, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(7, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(7, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(8, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(8, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(8, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(8, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(8, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(9, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(9, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(9, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(9, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(9, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(10, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(10, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(10, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(10, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(10, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(11, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(11, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(11, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(11, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(11, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(12, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(12, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(12, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(12, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(12, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(13, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(13, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(13, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(13, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(13, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(14, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(14, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(14, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(14, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(14, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(15, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(15, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(15, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(15, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(15, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(16, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(16, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(16, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(16, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(16, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(17, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(17, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(17, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(17, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(17, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(18, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(18, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(18, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(18, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(18, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(19, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(19, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(19, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(19, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(19, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(20, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(20, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(20, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(20, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(20, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(21, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(21, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(21, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(21, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(21, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(22, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(22, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(22, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(22, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(22, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(23, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(23, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(23, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(23, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(23, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(24, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(24, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(24, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(24, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(24, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(25, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(25, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(25, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(25, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(25, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(26, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(26, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(26, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(26, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(26, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(27, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(27, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(27, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(27, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(27, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(28, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(28, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(28, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(28, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(28, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(29, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(29, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(29, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(29, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(29, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(30, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(30, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(30, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(30, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(30, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(31, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(31, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(31, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(31, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(31, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(32, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(32, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(32, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(32, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(32, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(33, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(33, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(33, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(33, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(33, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(34, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(34, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(34, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(34, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(34, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(35, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(35, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(35, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(35, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(35, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(36, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(36, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(36, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(36, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(36, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(37, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(37, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(37, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(37, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(37, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(38, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(38, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(38, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(38, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(38, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(39, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(39, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(39, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(39, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(39, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(40, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(40, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(40, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(40, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(40, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(41, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(41, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(41, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(41, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(41, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(42, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(42, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(42, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(42, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(42, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(43, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(43, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(43, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(43, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(43, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(44, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(44, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(44, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(44, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(44, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(45, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(45, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(45, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(45, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(45, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(46, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(46, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(46, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(46, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(46, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(47, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(47, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(47, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(47, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(47, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(48, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(48, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(48, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(48, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(48, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(49, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(49, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(49, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(49, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(49, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(50, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(50, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(50, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(50, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(50, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(51, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(51, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(51, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(51, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(51, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(52, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(52, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(52, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(52, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(52, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(53, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(53, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(53, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(53, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(53, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(54, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(54, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(54, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(54, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(54, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(55, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(55, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(55, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(55, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(55, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(56, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(56, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(56, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(56, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(56, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(57, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(57, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(57, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(57, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(57, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(58, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(58, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(58, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(58, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(58, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(59, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(59, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(59, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(59, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(59, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(60, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(60, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(60, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(60, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(60, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(61, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(61, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(61, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(61, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(61, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(62, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(62, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(62, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(62, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(62, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(63, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(63, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(63, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(63, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(63, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(64, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(64, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(64, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(64, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(64, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(65, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(65, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(65, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(65, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(65, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(66, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(66, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(66, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(66, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(66, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(67, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(67, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(67, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(67, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(67, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(68, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(68, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(68, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(68, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(68, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(69, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(69, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(69, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(69, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(69, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(70, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(70, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(70, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(70, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(70, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(71, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(71, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(71, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(71, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(71, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(72, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(72, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(72, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(72, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(72, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(73, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(73, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(73, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(73, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(73, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(74, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(74, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(74, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(74, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(74, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(75, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(75, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(75, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(75, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(75, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(76, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(76, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(76, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(76, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(76, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(77, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(77, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(77, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(77, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(77, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(78, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(78, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(78, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(78, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(78, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(79, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(79, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(79, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(79, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(79, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(80, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(80, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(80, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(80, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(80, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(81, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(81, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(81, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(81, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(81, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(82, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(82, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(82, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(82, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(82, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(83, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(83, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(83, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(83, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(83, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(84, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(84, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(84, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(84, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(84, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(85, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(85, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(85, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(85, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(85, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(86, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(86, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(86, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(86, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(86, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(87, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(87, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(87, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(87, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(87, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(88, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(88, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(88, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(88, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(88, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(89, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(89, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(89, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(89, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(89, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(90, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(90, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(90, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(90, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(90, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(91, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(91, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(91, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(91, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(91, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(92, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(92, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(92, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(92, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(92, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(93, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(93, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(93, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(93, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(93, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(94, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(94, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(94, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(94, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(94, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(95, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(95, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(95, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(95, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(95, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(96, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(96, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(96, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(96, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(96, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(97, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(97, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(97, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(97, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(97, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(98, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(98, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(98, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(98, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(98, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(99, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(99, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(99, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(99, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(99, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.'),
(100, 1, '강의 소개', '이 섹션에서는 강의 개요와 기대할 수 있는 학습 내용을 설명합니다.'),
(100, 2, '환경 설정', '개발 환경 설정 및 필수 도구 설치를 다룹니다.'),
(100, 3, '핵심 개념 익히기', '기초 이론 및 주요 개념을 실습과 함께 학습합니다.'),
(100, 4, '실전 프로젝트', '실제 프로젝트를 통해 개념을 응용하고 실무 능력을 강화합니다.'),
(100, 5, '마무리 및 다음 단계', '학습 요약과 향후 학습 방향을 안내합니다.');